name: Setup Go
description: Setup Go environment with caching

runs:
  using: composite
  steps:
    - uses: actions/setup-go@v5
      with:
        go-version: '1.25'

    - name: Download dependencies
      shell: bash
      run: go mod download
